[server]
hostname = "localhost"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database_unique_id"

[database.identity_db]
driver = "com.mysql.jdbc.Driver"
url = "jdbc:mysql://wso2isdbinstance2.cd3cwezibdu8.us-east-1.rds.amazonaws.com:3306/IDENTITY_DB?useSSL=false&amp;rewriteBatchedStatements=true"
validation_query = "SELECT 1"
username = "wso2carbon"
password = "wso2carbon"
[database.identity_db.pool_options]
maxActive = "500"

[database.shared_db]
driver = "com.mysql.jdbc.Driver"
url = "jdbc:mysql://wso2isdbinstance2.cd3cwezibdu8.us-east-1.rds.amazonaws.com:3306/REG_DB?useSSL=false&amp;rewriteBatchedStatements=true"
validation_query = "SELECT 1"
username = "wso2carbon"
password = "wso2carbon"
[database.shared_db.pool_options]
maxActive = "500"

[database.user]
driver = "com.mysql.jdbc.Driver"
url = "jdbc:mysql://wso2isdbinstance2.cd3cwezibdu8.us-east-1.rds.amazonaws.com:3306/UM_DB?useSSL=false&amp;rewriteBatchedStatements=true"
validation_query = "SELECT 1"
username = "wso2carbon"
password = "wso2carbon"
[database.user.pool_options]
maxActive = "500"

[transport.https.properties]
maxThreads = "500"
acceptCount = "500"

[clustering]
#membership_scheme = true
#domain = "is590.qa.com"
membership_scheme = "wka"
local_member_host = "member_ip_1"
localMemberPort = "4000"
members = ["member_ip_2:4000", "member_ip_1:4000"]

[admin_service]
wsdl.enable=false

[keystore.primary]
file_name = "wso2carbon.jks"
password = "wso2carbon"

[truststore]
file_name="client-truststore.jks"
password="wso2carbon"
type="JKS"

[account_recovery.endpoint.auth]
hash= "66cd9688a2ae068244ea01e70f0e230f5623b7fa4cdecb65070a09ec06452262"

[identity.auth_framework.endpoint]
app_password= "dashboard"

[oauth.grant_type.jwt]
iat_validity_period=1440
